# version: '3' # now obsolete

# new top level element is 'name'
name: myapp_rails5_with_docker

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    # environment:
    #   DATABASE_HOST: database
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: some-long-password
    #   POSTGRES_DB: myapp_development
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server

  webpack_dev_server:
    # also build from the same Dockerfile as web
    build: .
    # override the default command to run the webpack-dev-server
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    # and share the same volume as web
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/web
      - .env/development/database
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    # depends_on:
    #   - web

  redis:
    image: "redis"

  database:
    image: postgres
    # environment:
    #   POSTGRES_USER: postgres # default value
    #   POSTGRES_PASSWORD: some-long-password
    #   POSTGRES_DB: myapp_development
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
