# version: '3' # now obsolete

# new top level element is 'name'
name: myapp_rails5_with_docker

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

  redis:
    image: "redis"

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres # default value
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
