# version: '3' # now obsolete

# new top level element is 'name'
name: myapp_rails5_with_docker

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    # environment:
    #   DATABASE_HOST: database
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: some-long-password
    #   POSTGRES_DB: myapp_development
    env_file:
      - .env/development/database
      - .env/development/web

  redis:
    image: "redis"

  database:
    image: postgres
    # environment:
    #   POSTGRES_USER: postgres # default value
    #   POSTGRES_PASSWORD: some-long-password
    #   POSTGRES_DB: myapp_development
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
